### ISSUE TITLE
CUDA tests still fail

### ISSUE THREAD

**Issue by edouardoyallon** [kymatio/kymatio#387]

**Comment by edouardoyallon** [comment]
okay my bad, it works perfectly fine - it's just that the way the console is read in github is different(like the output is not displayed as before). Do you know by chance if this is easy to fix?

**Comment by dylex** [comment]
I'm not sure I understand.  I do see the last few commits are failing, but these look like they might be real failures. Do you think they should be passing? Which output are you referring to?

**Comment by edouardoyallon** [comment]
Hey, it seems there is .. no more GPU, any suggestions? https://jenkins.flatironinstitute.org/job/kymatio/job/PR-382/8/console

Thanks!!
Edouard

**Comment by dylex** [comment]
Sorry, a recent update left things in an inconsistent state.  I'll try to keep an eye on future changes.

**Comment by edouardoyallon** [comment]
https://jenkins.flatironinstitute.org/job/kymatio/job/PR-390/4/console it seems that the software is stuck there...

**Comment by edouardoyallon** [comment]
Hi, in the recent PRs, there is this bug: https://jenkins.flatironinstitute.org/job/kymatio/job/PR-398/3/console not sure how to fix it.. Thanks!!

```Exception ignored in: 'cupy.cuda.function.Module.__dealloc__'
Traceback (most recent call last):
  File "cupy/cuda/driver.pyx", line 192, in cupy.cuda.driver.moduleUnload
  File "cupy/cuda/driver.pyx", line 81, in cupy.cuda.driver.check_status
cupy.cuda.driver.CUDADriverError: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered```

**Comment by edouardoyallon** [comment]
```(kymatio_dev) :~/kymatio$ pytest
====================================================================================== test session starts ======================================================================================
platform linux -- Python 3.7.3, pytest-4.6.3, py-1.8.0, pluggy-0.12.0
rootdir: /home/kymatio
collected 49 items                                                                                                                                                                              

kymatio/scattering1d/tests/test_filters.py .........                                                                                                                                      [ 18%]
kymatio/scattering1d/tests/test_scattering1d.py .........                                                                                                                                 [ 36%]
kymatio/scattering1d/tests/test_utils.py .....                                                                                                                                            [ 46%]
kymatio/scattering2d/tests/test_torch_scattering2d.py ............F.F.                                                                                                                    [ 79%]
kymatio/scattering3d/tests/test_scattering3d.py .......... ```

I can't reproduce this error on other machines.. this is bizarre. (the fact that 2D doesn't pass makes sens)

**Comment by janden** [comment]
Is this still happening? The checks on #398 suggest that Jenkins passes now.

**Comment by edouardoyallon** [comment]
I think it is fine.. sometimes it bugs but maybe it's worth closing this issue for now. Sorry for the possible noise..
