### ISSUE TITLE
DOC circle.ci is failing

### ISSUE THREAD

**Issue by edouardoyallon** [kymatio/kymatio#569]
```
ModuleNotFoundError: No module named 'tensorflow'
ModuleNotFoundError: No module named 'kymatio.scattering3d.core'
WARNING: autodoc: failed to import module 'numpy' from module 'kymatio'; the following exception was raised:
```

https://circleci.com/gh/kymatio/kymatio/147#tests/containers/0

**Comment by edouardoyallon** [comment]
```
WARNING: /home/circleci/repo/examples/1d/plot_real_signal.py failed to execute correctly: Traceback (most recent call last):
  File "/home/circleci/repo/venv/lib/python3.6/site-packages/sphinx_gallery/gen_rst.py", line 440, in _memory_usage
    out = func()
  File "/home/circleci/repo/venv/lib/python3.6/site-packages/sphinx_gallery/gen_rst.py", line 425, in __call__
    exec(self.code, self.globals)
  File "/home/circleci/repo/examples/1d/plot_real_signal.py", line 31, in <module>
    from kymatio.numpy import Scattering1D
  File "/home/circleci/repo/venv/lib/python3.6/site-packages/kymatio/numpy.py", line 3, in <module>
    from .scattering3d.frontend.numpy_frontend \
  File "/home/circleci/repo/venv/lib/python3.6/site-packages/kymatio/scattering3d/frontend/numpy_frontend.py", line 2, in <module>
    from ..core.scattering3d import scattering3d
ModuleNotFoundError: No module named 'kymatio.scattering3d.core'
```

Still there.

**Comment by edouardoyallon** [comment]
```
/home/circleci/repo/doc/source/gallery_1d/plot_real_signal.rst:17: WARNING: Unexpected section title or transition.

-------------
/home/circleci/repo/doc/source/gallery_1d/plot_real_signal.rst:19: WARNING: Missing matching underline for section title overline.
```

one could fix that too on the fly

**Comment by edouardoyallon** [comment]
I think this could be linked to: https://github.com/kymatio/kymatio/blob/master/kymatio/scattering2d/frontend/numpy_frontend.py#L2 -- that we probably do not desire. Any ideas?

**Comment by eickenberg** [comment]
This should be fixed now. Waiting for circleci to confirm

**Comment by eickenberg** [comment]
tic toc https://circleci.com/gh/kymatio/kymatio/184 almost there

**Comment by eickenberg** [comment]
![image](https://user-images.githubusercontent.com/1306635/75793996-264a9900-5d3e-11ea-9e9a-a38bad76374a.png)

**Comment by eickenberg** [comment]
![image](https://user-images.githubusercontent.com/1306635/75794064-424e3a80-5d3e-11ea-9284-10d780f9a23d.png)
