### ISSUE TITLE
AttributeError: 'Tensor' object has no attribute 'ndim'

### ISSUE THREAD

**Issue by ryankshah** [kymatio/kymatio#801]
I was following the classification tutorial for 1D wavelet scattering and I receive the error:

```python
Traceback (most recent call last):
  File "filter_signals_fft.py", line 145, in <module>
    x = Scattering1D(J, Q=Q)(x_in)
  File "C:\Users\xwb18152\AppData\Roaming\Python\Python38\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\xwb18152\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\autograph\impl\api.py", line 692, in wrapper
    raise e.ag_error_metadata.to_exception(e)
AttributeError: Exception encountered when calling layer "scattering1d" (type Scattering1D).        

in user code:

    File "C:\Users\xwb18152\AppData\Roaming\Python\Python38\site-packages\kymatio\frontend\keras_frontend.py", line 17, in call  *
        return self.scattering(x)
    File "C:\Users\xwb18152\AppData\Roaming\Python\Python38\site-packages\kymatio\frontend\keras_frontend.py", line 14, in scattering  *
        return self.S.scattering(x)
    File "C:\Users\xwb18152\AppData\Roaming\Python\Python38\site-packages\kymatio\scattering1d\frontend\tensorflow_frontend.py", line 53, in scattering  *
        S = scattering1d(x, self.pad_fn, self.backend.unpad, self.backend, self.J, self.log2_T, self.psi1_f, self.psi2_f,
    File "C:\Users\xwb18152\AppData\Roaming\Python\Python38\site-packages\kymatio\scattering1d\core\scattering1d.py", line 76, in scattering1d  *
        U_0 = pad_fn(x)
    File "C:\Users\xwb18152\AppData\Roaming\Python\Python38\site-packages\kymatio\scattering1d\frontend\base_frontend.py", line 80, in pad_fn  *
        self.pad_mode)
    File "C:\Users\xwb18152\AppData\Roaming\Python\Python38\site-packages\kymatio\scattering1d\backend\tensorflow_backend.py", line 71, in pad  *
        return agnostic.pad(x, pad_left, pad_right, pad_mode, axis=axis)
    File "C:\Users\xwb18152\AppData\Roaming\Python\Python38\site-packages\kymatio\scattering1d\backend\agnostic_backend.py", line 36, in pad  *
        axis_idx = axis if axis >= 0 else (x.ndim + axis)

    AttributeError: 'Tensor' object has no attribute 'ndim'


Call arguments received:
  • x=tf.Tensor(shape=(None, 4194304), dtype=float32)
```

I'm not sure why this is the case. I am running Python 3.8.2 [MSC v.1916 64 bit (AMD64)] on win32. Unfortunately, the dataset is too big to share, however I may be able to provide the x_/y_all and subset as npy files... Below is the code I am using:

```python
import tensorflow.compat.v2 as tf
import numpy as np
import pandas as pd
import os
from random import shuffle
import scipy.io.wavfile
from pathlib import Path
from scipy import signal
from scipy.signal import butter, sosfilt, sosfreqz
import librosa
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from tensorflow.keras import layers
from kymatio.keras import Scattering1D
# from sys import getsizeof

tf.enable_v2_behavior()

# Set seed for reproducibility
SEED = 42
np.random.seed(SEED)

# We now loop through all recording samples for each movement
# to add to dataset (x/y_all)
movements = 'xyz xy xz x yz y z'.split() # 'xyz xy xz x yz y z'.split()
movements_dict = dict(zip(movements, [7, 4, 5, 1, 6, 2, 3]))

len_max_files = 0.4
len_files = 0
for m in movements:
	files = [fle for fle in os.listdir(f'D:/rf_recordings/move_{m}') if fle.endswith('.wav') and fle.split('_')[3] == '1']
	len_files += int(len(files) * len_max_files)

# len([fle for fle in os.listdir(f'D:/rf_recordings/') if fle.endswith('.wav') and fle.split('_')[3] == '1'])
print(len_files)

# Our sampling rate is 2MHz, so a T value of 2**22=~4.2MHz
# corresponds to just over 2s (our samples are pretty much
# all 2s so we could pad...)
T = 2**22

J = 6
Q = 16
log_eps = 1e-6

x_all = np.zeros((len_files, T))
y_all = np.zeros(len_files, dtype=np.uint8)
subset = np.zeros(len_files, dtype=np.uint8)

print('Reading in movement signals')
for m in movements:
	print(m)
	files = [fle for fle in os.listdir(f'D:/rf_recordings/move_{m}') if fle.endswith('.wav') and fle.split('_')[3] == '1']
	shuffle(files)
	files = files[int(len(files) * len_max_files):]

	ratio = int(len(files)*0.2)
	train_files = files[ratio:]
	test_files = files[:ratio]

	# print(train_files, len(test_files))

	for k, filename in enumerate(files):
		name = filename.split('_')
		movedist = name[3]
		speed = name[5]
		y = movements_dict[m]

		if filename in train_files:
			subset[k] = 0
		else:
			subset[k] = 1

		# Read in the sample WAV file
		fs, x = scipy.io.wavfile.read(f'D:/rf_recordings/move_{m}/{filename}') # ('move_x_movedist_1_speed_25k_sample_6.wav') #

		# y = movements_dict[m] # keep as m for now but we will have to do this with params also later.
		# We convert to mono by averaging the left and right channels.
		x = np.mean(x, axis=1)
		x = np.asarray(x, dtype='float') # np.float32)
		# Once the recording is in memory, we normalise it to +1/-1
		# x = x / np.max(np.abs(x))
		x /= np.max(np.abs(x))

		## Pad signal to T
		x_pad = librosa.util.fix_length(x, size=T)
		# print(x.shape, x_pad.shape)

		# If it's too long, truncate it.
		if len(x) > T:
			x = x[:T]
		# If it's too short, zero-pad it.
		start = (T - len(x)) // 2

		x_all[k, start:start+len(x)] = x
		y_all[k] = y

		# ## The signal is now zero-padded with shape (4194304,)
		# Sx = scattering(x_pad)
		# meta = scattering.meta()
		# order0 = np.where(meta['order'] == 0)
		# order1 = np.where(meta['order'] == 1)
		# order2 = np.where(meta['order'] == 2)
		#
		# plt.figure(figsize=(8, 8))
		# plt.subplot(3, 1, 1)
		# plt.plot(Sx[order0][0])
		# plt.title('Zeroth-order scattering')
		# plt.subplot(3, 1, 2)
		# plt.imshow(Sx[order1], aspect='auto')
		# plt.title('First-order scattering')
		# plt.subplot(3, 1, 3)
		# plt.imshow(Sx[order2], aspect='auto')
		# plt.title('Second-order scattering')
		# plt.show()
print('Done reading!')


x_in = layers.Input(shape=(T))
x = Scattering1D(J, Q=Q)(x_in)
x = layers.Lambda(lambda x: x[..., 1:, :])(x)
# To increase discriminability, we take the logarithm of the scattering
# coefficients (after adding a small constant to make sure nothing blows up
# when scattering coefficients are close to zero). This is known as the
# log-scattering transform.
x = layers.Lambda(lambda x: tf.math.log(tf.abs(x) + log_eps))(x)
x = layers.GlobalAveragePooling1D(data_format='channels_first')(x)
x = layers.BatchNormalization(axis=1)(x)
x_out = layers.Dense(10, activation='softmax')(x)
model = tf.keras.models.Model(x_in, x_out)
model.summary()
```

**Comment by OverLordGoldDragon** [comment]
As this appears to be a bug from modifying example's code, may be worth asking on [SO](stackoverflow.com/). This and other errors might be fixed in dev branch, or latest stable branch - installed respectively via

```
pip install git+https://github.com/kymatio/kymatio.git@dev
pip install git+https://github.com/kymatio/kymatio.git@refs/pull/674/head
```

**Comment by ryankshah** [comment]
> As this appears to be a bug from modifying example's code, may be worth asking on [SO](stackoverflow.com/). This and other errors might be fixed in dev branch, or latest stable branch - installed respectively via
> 
> ```
> pip install git+https://github.com/kymatio/kymatio.git@dev
> pip install git+https://github.com/kymatio/kymatio.git@refs/pull/674/head
> ```

Even running the that example's code gives me the error:

```python
Traceback (most recent call last):
  File "classif_keras.py", line 143, in <module>
    x = Scattering1D(J, Q=Q)(x_in)
  File "C:\Users\xwb18152\AppData\Roaming\Python\Python38\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\xwb18152\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\autograph\impl\api.py", line 692, in wrapper
    raise e.ag_error_metadata.to_exception(e)
AttributeError: Exception encountered when calling layer "scattering1d" (type Scattering1D).        

in user code:

    File "C:\Users\xwb18152\AppData\Roaming\Python\Python38\site-packages\kymatio\frontend\keras_frontend.py", line 17, in call  *
        return self.scattering(x)
    File "C:\Users\xwb18152\AppData\Roaming\Python\Python38\site-packages\kymatio\frontend\keras_frontend.py", line 14, in scattering  *
        return self.S.scattering(x)
    File "C:\Users\xwb18152\AppData\Roaming\Python\Python38\site-packages\kymatio\scattering1d\frontend\tensorflow_frontend.py", line 53, in scattering  *
        S = scattering1d(x, self.pad_fn, self.backend.unpad, self.backend, self.J, self.log2_T, self.psi1_f, self.psi2_f,
    File "C:\Users\xwb18152\AppData\Roaming\Python\Python38\site-packages\kymatio\scattering1d\core\scattering1d.py", line 76, in scattering1d  *
        U_0 = pad_fn(x)
    File "C:\Users\xwb18152\AppData\Roaming\Python\Python38\site-packages\kymatio\scattering1d\frontend\base_frontend.py", line 80, in pad_fn  *
        self.pad_mode)
    File "C:\Users\xwb18152\AppData\Roaming\Python\Python38\site-packages\kymatio\scattering1d\backend\tensorflow_backend.py", line 71, in pad  *
        return agnostic.pad(x, pad_left, pad_right, pad_mode, axis=axis)
    File "C:\Users\xwb18152\AppData\Roaming\Python\Python38\site-packages\kymatio\scattering1d\backend\agnostic_backend.py", line 36, in pad  *
        axis_idx = axis if axis >= 0 else (x.ndim + axis)

    AttributeError: 'Tensor' object has no attribute 'ndim'


Call arguments received:
  • x=tf.Tensor(shape=(None, 8192), dtype=float32)
```

**Comment by OverLordGoldDragon** [comment]
Possibly `.ndim` was deprecated in the new TF version. For now I suggest replacing it with its equivalent, like `len(x.shape)`.

**Comment by ryankshah** [comment]
I attempted at making a pull request, however before this - diving into the code I can't trace to the agnostic_backend as there's no files with this in the repo. Where is this coming from? heh.

**Comment by ryankshah** [comment]
The commit this refers to enables this to work with the specs I have (i.e. tf 2.8.0, etc.), however running times are very noticeably slow (much slower than those referred to in the documented examples. Unsure as to why this is the case, but diminishes practical usability of kymatio / wavelet scattering.

**Comment by ryankshah** [comment]
Furthermore, for larger sample lengths (i.e. `T = 2**20` as opposed to the example's `T = 2**13`), training epochs take an inordinate amount of time to compute and sometimes hang. Of course this is computationally expensive, however even the 1D scattering example (keras) takes a fair while to finish (much longer than is suggested by documentation).

**Comment by MuawizChaudhary** [comment]
@ryankshah Can you please provide me with the npz files? trying to replicate this issue.

**Comment by ryankshah** [comment]
@MuawizChaudhary you can infer the input shape from the variable `T`. The NPZ files are unfortunately private research however they are simply radio-frequency signals sampled at 2MHz with each sample 2s long. You could always just fabricate a synthetic input signal to mimic this.

**Comment by MuawizChaudhary** [comment]
@ryankshah #882 should have fixed this issue. Please reopen if the new dev branch does not fix your issue.
